### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by iamdriz** [hraq/cake-intl#3]
I get an error: `Warning (2): require_once(/Locale.php): failed to open stream: No such file or directory [ROOT/plugins/CakeIntl/config/bootstrap.php, line 13]`

**Comment by hraq** [comment]
Hi,

there is no need to create any file by self. All needed files is in plugin.

Have you installed plugin via Composer (recomended) or download as zip and install it manually?

**Comment by iamdriz** [comment]
I did a var_dump on the $path in bootstrap.php and it shows it as bool(false) which is what realpath returns on failure. I installed it manually, so have a structure like:

`/plugins/CakeIntl/config/bootstrap.php`

And the $path looks like: `$path = realpath(__DIR__.'../../src/Lib');`

which returns this:

`"/html/plugins/CakeIntl/config../../src/Lib"`

Even if I change it to: `$path = realpath(__DIR__.'../src/Lib');` it doesn't work...

**Comment by hraq** [comment]
Thanks for reporting. As soon that I'm home i'll check and fix that.

**Comment by iamdriz** [comment]
@hraq How did you get on with this? Thanks

**Comment by hraq** [comment]
@iamdriz In vanilla CakePHP I haven't yet been able to replicate that error. I tried both, manual and via composer and both works fine.

Have you done any changes on Cake configuration (besides database connections etc)?

**Comment by iamdriz** [comment]
@hraq No I've added it to a fresh install of CakePHP as I need this plugin to allow Cake to run on a server that doesn't support the php intl extension.

**Comment by hraq** [comment]
@iamdriz I made little update. I'm not sure will it work, but I hope so.

**Comment by iamdriz** [comment]
@hraq Looks to fix it :)

**Comment by hraq** [comment]
@iamdriz Excellent!

Try if realpath is working correctly in your system. (realpath(**FILE**) => full path to file). If not work, it may cause other problems later when using 3rd party libraries.
